### ISSUE TITLE
support regex

### ISSUE THREAD

**Issue by joeltello** [shama/grunt-minjson#5]
Maybe something like this?
```
     minjson:        
        files: [
          expand: yes
          cwd: '<%= yeoman.app %>/static'
          src: ['**']
          dest: '<%= yeoman.dist %>/static'
        ]
```
